title: "Abir Sarkar"
description: "Cornell University"
url: ""
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

permalink: /writing/:year/:month/:day/:title/

collections:
  posts:
    output: true

exclude:
  - README.md
